# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: ojs/v1/events.proto
# Protobuf Python Version: 7.35.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    1,
    '',
    'ojs/v1/events.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import struct_pb2 as google_dot_protobuf_dot_struct__pb2
from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x13ojs/v1/events.proto\x12\x06ojs.v1\x1a\x1cgoogle/protobuf/struct.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\xbd\x01\n\x05\x45vent\x12\n\n\x02id\x18\x01 \x01(\t\x12\x0c\n\x04type\x18\x02 \x01(\t\x12\x0e\n\x06job_id\x18\x03 \x01(\t\x12\x10\n\x08job_type\x18\x04 \x01(\t\x12\r\n\x05queue\x18\x05 \x01(\t\x12-\n\ttimestamp\x18\x06 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12%\n\x04\x64\x61ta\x18\x07 \x01(\x0b\x32\x17.google.protobuf.Struct\x12\x13\n\x0bworkflow_id\x18\x08 \x01(\t\"_\n\x13StreamEventsRequest\x12\x0e\n\x06queues\x18\x01 \x03(\t\x12\x13\n\x0b\x65vent_types\x18\x02 \x03(\t\x12\x0e\n\x06job_id\x18\x03 \x01(\t\x12\x13\n\x0bworkflow_id\x18\x04 \x01(\tBP\n\x16org.openjobspec.ojs.v1P\x01Z4github.com/openjobspec/ojs-proto/gen/go/ojs/v1;ojsv1b\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'ojs.v1.events_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\026org.openjobspec.ojs.v1P\001Z4github.com/openjobspec/ojs-proto/gen/go/ojs/v1;ojsv1'
  _globals['_EVENT']._serialized_start=95
  _globals['_EVENT']._serialized_end=284
  _globals['_STREAMEVENTSREQUEST']._serialized_start=286
  _globals['_STREAMEVENTSREQUEST']._serialized_end=381
# @@protoc_insertion_point(module_scope)
