# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from ojs._generated.ojs.v1 import events_pb2 as ojs_dot_v1_dot_events__pb2
from ojs._generated.ojs.v1 import job_pb2 as ojs_dot_v1_dot_job__pb2
from ojs._generated.ojs.v1 import queue_pb2 as ojs_dot_v1_dot_queue__pb2
from ojs._generated.ojs.v1 import service_pb2 as ojs_dot_v1_dot_service__pb2
from ojs._generated.ojs.v1 import worker_pb2 as ojs_dot_v1_dot_worker__pb2
from ojs._generated.ojs.v1 import workflow_pb2 as ojs_dot_v1_dot_workflow__pb2

GRPC_GENERATED_VERSION = '1.83.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in ojs/v1/service_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class OJSServiceStub:
    """OJSService is the gRPC service for the Open Job Spec protocol binding.

    Implementations MUST implement all RPCs corresponding to their declared
    conformance level. Implementations MUST NOT remove or rename any RPC method;
    unsupported methods MUST return UNIMPLEMENTED.

    Conformance levels:
    Level 0 (Core):          Manifest, Health, Enqueue, Fetch, Ack, Nack, ListQueues
    Level 1 (Reliable):      Level 0 + GetJob, CancelJob, Heartbeat, ListDeadLetter,
    RetryDeadLetter, DeleteDeadLetter
    Level 2 (Scheduled):     Level 1 + RegisterCron, UnregisterCron, ListCron
    Level 3 (Orchestration): Level 2 + CreateWorkflow, GetWorkflow, CancelWorkflow
    Level 4 (Advanced):      Level 3 + EnqueueBatch, QueueStats, PauseQueue, ResumeQueue
    Optional (any level):    StreamJobs, StreamEvents

    See: ojs-grpc-binding.md Section 5 (Protobuf Service Definition),
    Section 15 (Conformance Requirements)
    See: ojs-conformance.md
    ===========================================================================
    System RPCs
    ===========================================================================
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Manifest = channel.unary_unary(
                '/ojs.v1.OJSService/Manifest',
                request_serializer=ojs_dot_v1_dot_service__pb2.ManifestRequest.SerializeToString,
                response_deserializer=ojs_dot_v1_dot_service__pb2.ManifestResponse.FromString,
                _registered_method=True)
        self.Health = channel.unary_unary(
                '/ojs.v1.OJSService/Health',
                request_serializer=ojs_dot_v1_dot_service__pb2.HealthRequest.SerializeToString,
                response_deserializer=ojs_dot_v1_dot_service__pb2.HealthResponse.FromString,
                _registered_method=True)
        self.Enqueue = channel.unary_unary(
                '/ojs.v1.OJSService/Enqueue',
                request_serializer=ojs_dot_v1_dot_job__pb2.EnqueueRequest.SerializeToString,
                response_deserializer=ojs_dot_v1_dot_job__pb2.EnqueueResponse.FromString,
                _registered_method=True)
        self.EnqueueBatch = channel.unary_unary(
                '/ojs.v1.OJSService/EnqueueBatch',
                request_serializer=ojs_dot_v1_dot_job__pb2.EnqueueBatchRequest.SerializeToString,
                response_deserializer=ojs_dot_v1_dot_job__pb2.EnqueueBatchResponse.FromString,
                _registered_method=True)
        self.GetJob = channel.unary_unary(
                '/ojs.v1.OJSService/GetJob',
                request_serializer=ojs_dot_v1_dot_job__pb2.GetJobRequest.SerializeToString,
                response_deserializer=ojs_dot_v1_dot_job__pb2.GetJobResponse.FromString,
                _registered_method=True)
        self.CancelJob = channel.unary_unary(
                '/ojs.v1.OJSService/CancelJob',
                request_serializer=ojs_dot_v1_dot_job__pb2.CancelJobRequest.SerializeToString,
                response_deserializer=ojs_dot_v1_dot_job__pb2.CancelJobResponse.FromString,
                _registered_method=True)
        self.Fetch = channel.unary_unary(
                '/ojs.v1.OJSService/Fetch',
                request_serializer=ojs_dot_v1_dot_worker__pb2.FetchRequest.SerializeToString,
                response_deserializer=ojs_dot_v1_dot_worker__pb2.FetchResponse.FromString,
                _registered_method=True)
        self.Ack = channel.unary_unary(
                '/ojs.v1.OJSService/Ack',
                request_serializer=ojs_dot_v1_dot_worker__pb2.AckRequest.SerializeToString,
                response_deserializer=ojs_dot_v1_dot_worker__pb2.AckResponse.FromString,
                _registered_method=True)
        self.Nack = channel.unary_unary(
                '/ojs.v1.OJSService/Nack',
                request_serializer=ojs_dot_v1_dot_worker__pb2.NackRequest.SerializeToString,
                response_deserializer=ojs_dot_v1_dot_worker__pb2.NackResponse.FromString,
                _registered_method=True)
        self.Heartbeat = channel.unary_unary(
                '/ojs.v1.OJSService/Heartbeat',
                request_serializer=ojs_dot_v1_dot_worker__pb2.HeartbeatRequest.SerializeToString,
                response_deserializer=ojs_dot_v1_dot_worker__pb2.HeartbeatResponse.FromString,
                _registered_method=True)
        self.StreamJobs = channel.unary_stream(
                '/ojs.v1.OJSService/StreamJobs',
                request_serializer=ojs_dot_v1_dot_worker__pb2.StreamJobsRequest.SerializeToString,
                response_deserializer=ojs_dot_v1_dot_job__pb2.Job.FromString,
                _registered_method=True)
        self.StreamEvents = channel.unary_stream(
                '/ojs.v1.OJSService/StreamEvents',
                request_serializer=ojs_dot_v1_dot_events__pb2.StreamEventsRequest.SerializeToString,
                response_deserializer=ojs_dot_v1_dot_events__pb2.Event.FromString,
                _registered_method=True)
        self.ListQueues = channel.unary_unary(
                '/ojs.v1.OJSService/ListQueues',
                request_serializer=ojs_dot_v1_dot_queue__pb2.ListQueuesRequest.SerializeToString,
                response_deserializer=ojs_dot_v1_dot_queue__pb2.ListQueuesResponse.FromString,
                _registered_method=True)
        self.QueueStats = channel.unary_unary(
                '/ojs.v1.OJSService/QueueStats',
                request_serializer=ojs_dot_v1_dot_queue__pb2.QueueStatsRequest.SerializeToString,
                response_deserializer=ojs_dot_v1_dot_queue__pb2.QueueStatsResponse.FromString,
                _registered_method=True)
        self.PauseQueue = channel.unary_unary(
                '/ojs.v1.OJSService/PauseQueue',
                request_serializer=ojs_dot_v1_dot_queue__pb2.PauseQueueRequest.SerializeToString,
                response_deserializer=ojs_dot_v1_dot_queue__pb2.PauseQueueResponse.FromString,
                _registered_method=True)
        self.ResumeQueue = channel.unary_unary(
                '/ojs.v1.OJSService/ResumeQueue',
                request_serializer=ojs_dot_v1_dot_queue__pb2.ResumeQueueRequest.SerializeToString,
                response_deserializer=ojs_dot_v1_dot_queue__pb2.ResumeQueueResponse.FromString,
                _registered_method=True)
        self.ListDeadLetter = channel.unary_unary(
                '/ojs.v1.OJSService/ListDeadLetter',
                request_serializer=ojs_dot_v1_dot_queue__pb2.ListDeadLetterRequest.SerializeToString,
                response_deserializer=ojs_dot_v1_dot_queue__pb2.ListDeadLetterResponse.FromString,
                _registered_method=True)
        self.RetryDeadLetter = channel.unary_unary(
                '/ojs.v1.OJSService/RetryDeadLetter',
                request_serializer=ojs_dot_v1_dot_queue__pb2.RetryDeadLetterRequest.SerializeToString,
                response_deserializer=ojs_dot_v1_dot_queue__pb2.RetryDeadLetterResponse.FromString,
                _registered_method=True)
        self.DeleteDeadLetter = channel.unary_unary(
                '/ojs.v1.OJSService/DeleteDeadLetter',
                request_serializer=ojs_dot_v1_dot_queue__pb2.DeleteDeadLetterRequest.SerializeToString,
                response_deserializer=ojs_dot_v1_dot_queue__pb2.DeleteDeadLetterResponse.FromString,
                _registered_method=True)
        self.RegisterCron = channel.unary_unary(
                '/ojs.v1.OJSService/RegisterCron',
                request_serializer=ojs_dot_v1_dot_service__pb2.RegisterCronRequest.SerializeToString,
                response_deserializer=ojs_dot_v1_dot_service__pb2.RegisterCronResponse.FromString,
                _registered_method=True)
        self.UnregisterCron = channel.unary_unary(
                '/ojs.v1.OJSService/UnregisterCron',
                request_serializer=ojs_dot_v1_dot_service__pb2.UnregisterCronRequest.SerializeToString,
                response_deserializer=ojs_dot_v1_dot_service__pb2.UnregisterCronResponse.FromString,
                _registered_method=True)
        self.ListCron = channel.unary_unary(
                '/ojs.v1.OJSService/ListCron',
                request_serializer=ojs_dot_v1_dot_service__pb2.ListCronRequest.SerializeToString,
                response_deserializer=ojs_dot_v1_dot_service__pb2.ListCronResponse.FromString,
                _registered_method=True)
        self.CreateWorkflow = channel.unary_unary(
                '/ojs.v1.OJSService/CreateWorkflow',
                request_serializer=ojs_dot_v1_dot_workflow__pb2.CreateWorkflowRequest.SerializeToString,
                response_deserializer=ojs_dot_v1_dot_workflow__pb2.CreateWorkflowResponse.FromString,
                _registered_method=True)
        self.GetWorkflow = channel.unary_unary(
                '/ojs.v1.OJSService/GetWorkflow',
                request_serializer=ojs_dot_v1_dot_workflow__pb2.GetWorkflowRequest.SerializeToString,
                response_deserializer=ojs_dot_v1_dot_workflow__pb2.GetWorkflowResponse.FromString,
                _registered_method=True)
        self.CancelWorkflow = channel.unary_unary(
                '/ojs.v1.OJSService/CancelWorkflow',
                request_serializer=ojs_dot_v1_dot_workflow__pb2.CancelWorkflowRequest.SerializeToString,
                response_deserializer=ojs_dot_v1_dot_workflow__pb2.CancelWorkflowResponse.FromString,
                _registered_method=True)
        self.SaveCheckpoint = channel.unary_unary(
                '/ojs.v1.OJSService/SaveCheckpoint',
                request_serializer=ojs_dot_v1_dot_service__pb2.SaveCheckpointRequest.SerializeToString,
                response_deserializer=ojs_dot_v1_dot_service__pb2.SaveCheckpointResponse.FromString,
                _registered_method=True)
        self.GetCheckpoint = channel.unary_unary(
                '/ojs.v1.OJSService/GetCheckpoint',
                request_serializer=ojs_dot_v1_dot_service__pb2.GetCheckpointRequest.SerializeToString,
                response_deserializer=ojs_dot_v1_dot_service__pb2.GetCheckpointResponse.FromString,
                _registered_method=True)
        self.DeleteCheckpoint = channel.unary_unary(
                '/ojs.v1.OJSService/DeleteCheckpoint',
                request_serializer=ojs_dot_v1_dot_service__pb2.DeleteCheckpointRequest.SerializeToString,
                response_deserializer=ojs_dot_v1_dot_service__pb2.DeleteCheckpointResponse.FromString,
                _registered_method=True)


class OJSServiceServicer:
    """OJSService is the gRPC service for the Open Job Spec protocol binding.

    Implementations MUST implement all RPCs corresponding to their declared
    conformance level. Implementations MUST NOT remove or rename any RPC method;
    unsupported methods MUST return UNIMPLEMENTED.

    Conformance levels:
    Level 0 (Core):          Manifest, Health, Enqueue, Fetch, Ack, Nack, ListQueues
    Level 1 (Reliable):      Level 0 + GetJob, CancelJob, Heartbeat, ListDeadLetter,
    RetryDeadLetter, DeleteDeadLetter
    Level 2 (Scheduled):     Level 1 + RegisterCron, UnregisterCron, ListCron
    Level 3 (Orchestration): Level 2 + CreateWorkflow, GetWorkflow, CancelWorkflow
    Level 4 (Advanced):      Level 3 + EnqueueBatch, QueueStats, PauseQueue, ResumeQueue
    Optional (any level):    StreamJobs, StreamEvents

    See: ojs-grpc-binding.md Section 5 (Protobuf Service Definition),
    Section 15 (Conformance Requirements)
    See: ojs-conformance.md
    ===========================================================================
    System RPCs
    ===========================================================================
    """

    def Manifest(self, request, context):
        """Returns the conformance manifest for this OJS implementation.

        The manifest declares the implementation name, version, conformance level,
        supported protocols, backend type, and enabled extensions. Clients use
        this to discover server capabilities at runtime.

        Conformance level: 0 (Core).

        See: ojs-conformance.md (Conformance Manifest)
        See: ojs-grpc-binding.md Section 6.2 (Manifest)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Health(self, request, context):
        """Returns the health status of the OJS server and its backend.

        Implementations SHOULD also implement the standard gRPC Health Checking
        Protocol (grpc.health.v1.Health) for Kubernetes and load balancer
        compatibility.

        Conformance level: 0 (Core).

        See: ojs-grpc-binding.md Section 6.2 (Health), Section 15.3
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Enqueue(self, request, context):
        """===========================================================================
        Job RPCs
        ===========================================================================

        Enqueues a single job. Maps to the PUSH logical operation.

        The implementation validates the job envelope, assigns system-managed
        attributes (id, state, created_at, enqueued_at), and returns the
        complete job envelope.

        Conformance level: 0 (Core).

        See: ojs-core.md Section 7.1 (PUSH)
        See: ojs-grpc-binding.md Section 4 (Logical Operation Mapping)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def EnqueueBatch(self, request, context):
        """Enqueues multiple jobs atomically. Maps to PUSH (batch).

        Either all jobs in the batch MUST be enqueued or none. Supports
        default options that apply to all jobs, with per-job overrides.

        Conformance level: 4 (Advanced).

        See: ojs-core.md Section 7.1 (Batch variant)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetJob(self, request, context):
        """Retrieves the current state and data of a job by ID.
        Maps to the INFO logical operation.

        This is a read-only operation with no side effects. Returns NOT_FOUND
        if the job does not exist.

        Conformance level: 1 (Reliable).

        See: ojs-core.md Section 7.7 (INFO)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CancelJob(self, request, context):
        """Cancels a job that has not yet reached a terminal state.
        Maps to the CANCEL logical operation.

        Cancellation is idempotent: cancelling an already-cancelled job
        succeeds without error.

        Conformance level: 1 (Reliable).

        See: ojs-core.md Section 7.6 (CANCEL)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Fetch(self, request, context):
        """===========================================================================
        Worker RPCs
        ===========================================================================

        Fetches one or more jobs from the specified queues for processing.
        Maps to the FETCH logical operation. This is the unary (polling) variant.

        The implementation selects the highest-priority available job from the
        specified queues (checked in left-to-right order). The job transitions
        to active atomically.

        Conformance level: 0 (Core).

        See: ojs-core.md Section 7.2 (FETCH)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Ack(self, request, context):
        """Acknowledges successful completion of a job.
        Maps to the ACK logical operation.

        The job transitions from active to completed. Optional result data
        is stored in the job's result attribute.

        Conformance level: 0 (Core).

        See: ojs-core.md Section 7.3 (ACK)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Nack(self, request, context):
        """Reports job failure with structured error information.
        Maps to the FAIL logical operation.

        The implementation evaluates the retry policy and transitions the job
        to either retryable (if attempts remain) or discarded (if exhausted).

        Conformance level: 0 (Core).

        See: ojs-core.md Section 7.4 (FAIL)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Heartbeat(self, request, context):
        """Extends the visibility timeout for an active job and reports worker state.
        Maps to the BEAT logical operation.

        The server MAY respond with a directive to change the worker's lifecycle
        state (running, quiet, terminate).

        Conformance level: 1 (Reliable).

        See: ojs-core.md Section 7.5 (BEAT), Section 10 (Worker Lifecycle)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StreamJobs(self, request, context):
        """===========================================================================
        Streaming RPCs
        ===========================================================================

        Opens a server-streaming connection that pushes jobs to the worker
        as they become available. High-throughput alternative to polling via Fetch.

        ## Flow Control

        The server tracks in-flight (unacknowledged) jobs per stream and MUST NOT
        push more jobs than the client's `max_concurrent` limit minus in-flight
        count. When `in_flight == max_concurrent`, the server blocks until an
        Ack or Nack is received via unary RPCs. Each job delivered on the stream
        MUST be acknowledged via a separate Ack or Nack unary RPC — the stream
        itself does not carry acknowledgments.

        ## Backpressure

        Server-side: when the gRPC transport flow-control window fills (client
        stops reading), the server MUST stop fetching from the backend. The
        concurrency token model (`tokens = max_concurrent - in_flight`) provides
        application-level backpressure on top of gRPC transport backpressure.

        ## Message Ordering

        Within a single queue, jobs are delivered in priority order (highest
        first), then FIFO within the same priority. Across queues, delivery
        follows the left-to-right priority of StreamJobsRequest.queues. No
        total ordering is guaranteed across queues or when multiple jobs have
        equal priority.

        ## Reconnection Behavior

        Streams are ephemeral. On disconnect (server-initiated or network):
        - Unacknowledged jobs are NOT automatically failed; they are reclaimed
        by the backend after their visibility_timeout expires.
        - Clients SHOULD finish processing in-progress jobs and ACK/NACK them
        via unary RPCs (which use a separate connection).
        - Clients MUST reconnect with exponential backoff: start at 100ms,
        double each attempt, cap at 30s, with ±25% jitter. Reset the
        backoff after a stream successfully delivers at least one job.
        - The same job MAY be re-delivered on a new stream if the prior
        delivery was not ACKed before the visibility timeout. Handlers
        MUST be idempotent.

        ## Error Codes

        UNAVAILABLE        — Server overloaded; reconnect with backoff.
        RESOURCE_EXHAUSTED — Too many concurrent streams; back off.
        INVALID_ARGUMENT   — Bad request (empty queues, invalid max_concurrent).
        UNAUTHENTICATED    — Missing/invalid credentials; re-authenticate.
        PERMISSION_DENIED  — Not authorized for requested queues.
        UNIMPLEMENTED      — Server does not support StreamJobs; use Fetch.

        ## Keepalive

        The server SHOULD send a keepalive message (Job with type
        "stream.keepalive" and empty args) every 30 seconds on idle streams.
        Clients MUST filter keepalives and SHOULD assume the stream is dead
        if no message is received for 90 seconds.

        Conformance level: OPTIONAL (any level).

        See: ojs-grpc-binding.md Section 10.1 (StreamJobs semantics)
        See: docs/STREAMING.md for implementation guide with code examples
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StreamEvents(self, request, context):
        """Opens a server-streaming connection that delivers real-time lifecycle
        events. Used for monitoring dashboards and observability tooling.

        ## Delivery Guarantees

        Events are delivered on a **best-effort** basis. Under extreme load,
        events MAY be dropped. There is no replay, offset, or cursor mechanism —
        events emitted during a client disconnection are lost. The same event
        MAY be delivered more than once during server failover.

        ## Flow Control and Backpressure

        The server buffers events when the client is slow to consume
        (recommended buffer: 1000 events). On overflow, the server SHOULD
        drop the oldest events (not newest) and track a dropped-events counter.
        No client acknowledgment is required — events are fire-and-forget.

        ## Message Ordering

        Events are delivered in approximately chronological order. Strict
        ordering is NOT guaranteed across concurrent job completions on
        different workers.

        ## Reconnection Behavior

        On disconnect, the client loses any buffered events. Reconnection
        strategy is the same as StreamJobs: exponential backoff with jitter
        (100ms initial, 30s cap, ±25% jitter). There is no "resume from"
        mechanism — the client opens a fresh stream.

        ## Error Codes

        UNAVAILABLE      — Server overloaded; reconnect with backoff.
        INVALID_ARGUMENT — Bad filter parameters; fix request.
        UNAUTHENTICATED  — Missing credentials; re-authenticate.
        UNIMPLEMENTED    — Server does not support StreamEvents; use webhooks.

        ## Keepalive

        The server SHOULD send a keepalive event (type "stream.keepalive")
        every 30 seconds on idle streams. Clients SHOULD filter keepalive
        events before processing and SHOULD assume the stream is dead if no
        message is received for 90 seconds.

        Conformance level: OPTIONAL (any level).

        See: ojs-grpc-binding.md Section 10.2 (StreamEvents semantics)
        See: docs/STREAMING.md for implementation guide with code examples
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListQueues(self, request, context):
        """===========================================================================
        Queue RPCs
        ===========================================================================

        Lists all known queues.

        Conformance level: 0 (Core).
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def QueueStats(self, request, context):
        """Returns statistics for a specific queue.

        Conformance level: 4 (Advanced).
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def PauseQueue(self, request, context):
        """Pauses a queue, preventing workers from fetching new jobs from it.
        Active jobs in the queue are not affected.

        Conformance level: 4 (Advanced).
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ResumeQueue(self, request, context):
        """Resumes a previously paused queue.

        Conformance level: 4 (Advanced).
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListDeadLetter(self, request, context):
        """===========================================================================
        Dead Letter RPCs
        ===========================================================================

        Lists jobs in the dead letter queue.

        Conformance level: 1 (Reliable).
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RetryDeadLetter(self, request, context):
        """Retries a specific dead letter job by re-enqueueing it.

        Conformance level: 1 (Reliable).

        See: ojs-core.md Section 6.3 (discarded -> available transition)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteDeadLetter(self, request, context):
        """Permanently deletes a dead letter job.

        Conformance level: 1 (Reliable).
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RegisterCron(self, request, context):
        """===========================================================================
        Cron RPCs
        ===========================================================================

        Registers a new cron (periodic) job schedule.

        Conformance level: 2 (Scheduled).

        See: ojs-cron.md
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UnregisterCron(self, request, context):
        """Removes a registered cron job schedule.

        Conformance level: 2 (Scheduled).

        See: ojs-cron.md
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListCron(self, request, context):
        """Lists all registered cron job schedules.

        Conformance level: 2 (Scheduled).

        See: ojs-cron.md
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CreateWorkflow(self, request, context):
        """===========================================================================
        Workflow RPCs
        ===========================================================================

        Creates and starts a new workflow.

        Conformance level: 3 (Orchestration).

        See: ojs-workflows.md
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetWorkflow(self, request, context):
        """Retrieves the current state of a workflow and all its steps.

        Conformance level: 3 (Orchestration).

        See: ojs-workflows.md
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CancelWorkflow(self, request, context):
        """Cancels a running workflow and all of its pending/active steps.

        Conformance level: 3 (Orchestration).

        See: ojs-workflows.md
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SaveCheckpoint(self, request, context):
        """─── Durable Execution (Checkpoints) ────────────────────────────────

        SaveCheckpoint saves execution state for a running job, enabling
        resumption from the last checkpoint if the job is retried.

        Extension: ojs-durable-execution.

        See: ojs-durable-execution.md Section 4
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetCheckpoint(self, request, context):
        """GetCheckpoint retrieves the most recent checkpoint for a job.

        Extension: ojs-durable-execution.

        See: ojs-durable-execution.md Section 4
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteCheckpoint(self, request, context):
        """DeleteCheckpoint removes the checkpoint for a job.

        Extension: ojs-durable-execution.

        See: ojs-durable-execution.md Section 4
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_OJSServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Manifest': grpc.unary_unary_rpc_method_handler(
                    servicer.Manifest,
                    request_deserializer=ojs_dot_v1_dot_service__pb2.ManifestRequest.FromString,
                    response_serializer=ojs_dot_v1_dot_service__pb2.ManifestResponse.SerializeToString,
            ),
            'Health': grpc.unary_unary_rpc_method_handler(
                    servicer.Health,
                    request_deserializer=ojs_dot_v1_dot_service__pb2.HealthRequest.FromString,
                    response_serializer=ojs_dot_v1_dot_service__pb2.HealthResponse.SerializeToString,
            ),
            'Enqueue': grpc.unary_unary_rpc_method_handler(
                    servicer.Enqueue,
                    request_deserializer=ojs_dot_v1_dot_job__pb2.EnqueueRequest.FromString,
                    response_serializer=ojs_dot_v1_dot_job__pb2.EnqueueResponse.SerializeToString,
            ),
            'EnqueueBatch': grpc.unary_unary_rpc_method_handler(
                    servicer.EnqueueBatch,
                    request_deserializer=ojs_dot_v1_dot_job__pb2.EnqueueBatchRequest.FromString,
                    response_serializer=ojs_dot_v1_dot_job__pb2.EnqueueBatchResponse.SerializeToString,
            ),
            'GetJob': grpc.unary_unary_rpc_method_handler(
                    servicer.GetJob,
                    request_deserializer=ojs_dot_v1_dot_job__pb2.GetJobRequest.FromString,
                    response_serializer=ojs_dot_v1_dot_job__pb2.GetJobResponse.SerializeToString,
            ),
            'CancelJob': grpc.unary_unary_rpc_method_handler(
                    servicer.CancelJob,
                    request_deserializer=ojs_dot_v1_dot_job__pb2.CancelJobRequest.FromString,
                    response_serializer=ojs_dot_v1_dot_job__pb2.CancelJobResponse.SerializeToString,
            ),
            'Fetch': grpc.unary_unary_rpc_method_handler(
                    servicer.Fetch,
                    request_deserializer=ojs_dot_v1_dot_worker__pb2.FetchRequest.FromString,
                    response_serializer=ojs_dot_v1_dot_worker__pb2.FetchResponse.SerializeToString,
            ),
            'Ack': grpc.unary_unary_rpc_method_handler(
                    servicer.Ack,
                    request_deserializer=ojs_dot_v1_dot_worker__pb2.AckRequest.FromString,
                    response_serializer=ojs_dot_v1_dot_worker__pb2.AckResponse.SerializeToString,
            ),
            'Nack': grpc.unary_unary_rpc_method_handler(
                    servicer.Nack,
                    request_deserializer=ojs_dot_v1_dot_worker__pb2.NackRequest.FromString,
                    response_serializer=ojs_dot_v1_dot_worker__pb2.NackResponse.SerializeToString,
            ),
            'Heartbeat': grpc.unary_unary_rpc_method_handler(
                    servicer.Heartbeat,
                    request_deserializer=ojs_dot_v1_dot_worker__pb2.HeartbeatRequest.FromString,
                    response_serializer=ojs_dot_v1_dot_worker__pb2.HeartbeatResponse.SerializeToString,
            ),
            'StreamJobs': grpc.unary_stream_rpc_method_handler(
                    servicer.StreamJobs,
                    request_deserializer=ojs_dot_v1_dot_worker__pb2.StreamJobsRequest.FromString,
                    response_serializer=ojs_dot_v1_dot_job__pb2.Job.SerializeToString,
            ),
            'StreamEvents': grpc.unary_stream_rpc_method_handler(
                    servicer.StreamEvents,
                    request_deserializer=ojs_dot_v1_dot_events__pb2.StreamEventsRequest.FromString,
                    response_serializer=ojs_dot_v1_dot_events__pb2.Event.SerializeToString,
            ),
            'ListQueues': grpc.unary_unary_rpc_method_handler(
                    servicer.ListQueues,
                    request_deserializer=ojs_dot_v1_dot_queue__pb2.ListQueuesRequest.FromString,
                    response_serializer=ojs_dot_v1_dot_queue__pb2.ListQueuesResponse.SerializeToString,
            ),
            'QueueStats': grpc.unary_unary_rpc_method_handler(
                    servicer.QueueStats,
                    request_deserializer=ojs_dot_v1_dot_queue__pb2.QueueStatsRequest.FromString,
                    response_serializer=ojs_dot_v1_dot_queue__pb2.QueueStatsResponse.SerializeToString,
            ),
            'PauseQueue': grpc.unary_unary_rpc_method_handler(
                    servicer.PauseQueue,
                    request_deserializer=ojs_dot_v1_dot_queue__pb2.PauseQueueRequest.FromString,
                    response_serializer=ojs_dot_v1_dot_queue__pb2.PauseQueueResponse.SerializeToString,
            ),
            'ResumeQueue': grpc.unary_unary_rpc_method_handler(
                    servicer.ResumeQueue,
                    request_deserializer=ojs_dot_v1_dot_queue__pb2.ResumeQueueRequest.FromString,
                    response_serializer=ojs_dot_v1_dot_queue__pb2.ResumeQueueResponse.SerializeToString,
            ),
            'ListDeadLetter': grpc.unary_unary_rpc_method_handler(
                    servicer.ListDeadLetter,
                    request_deserializer=ojs_dot_v1_dot_queue__pb2.ListDeadLetterRequest.FromString,
                    response_serializer=ojs_dot_v1_dot_queue__pb2.ListDeadLetterResponse.SerializeToString,
            ),
            'RetryDeadLetter': grpc.unary_unary_rpc_method_handler(
                    servicer.RetryDeadLetter,
                    request_deserializer=ojs_dot_v1_dot_queue__pb2.RetryDeadLetterRequest.FromString,
                    response_serializer=ojs_dot_v1_dot_queue__pb2.RetryDeadLetterResponse.SerializeToString,
            ),
            'DeleteDeadLetter': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteDeadLetter,
                    request_deserializer=ojs_dot_v1_dot_queue__pb2.DeleteDeadLetterRequest.FromString,
                    response_serializer=ojs_dot_v1_dot_queue__pb2.DeleteDeadLetterResponse.SerializeToString,
            ),
            'RegisterCron': grpc.unary_unary_rpc_method_handler(
                    servicer.RegisterCron,
                    request_deserializer=ojs_dot_v1_dot_service__pb2.RegisterCronRequest.FromString,
                    response_serializer=ojs_dot_v1_dot_service__pb2.RegisterCronResponse.SerializeToString,
            ),
            'UnregisterCron': grpc.unary_unary_rpc_method_handler(
                    servicer.UnregisterCron,
                    request_deserializer=ojs_dot_v1_dot_service__pb2.UnregisterCronRequest.FromString,
                    response_serializer=ojs_dot_v1_dot_service__pb2.UnregisterCronResponse.SerializeToString,
            ),
            'ListCron': grpc.unary_unary_rpc_method_handler(
                    servicer.ListCron,
                    request_deserializer=ojs_dot_v1_dot_service__pb2.ListCronRequest.FromString,
                    response_serializer=ojs_dot_v1_dot_service__pb2.ListCronResponse.SerializeToString,
            ),
            'CreateWorkflow': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateWorkflow,
                    request_deserializer=ojs_dot_v1_dot_workflow__pb2.CreateWorkflowRequest.FromString,
                    response_serializer=ojs_dot_v1_dot_workflow__pb2.CreateWorkflowResponse.SerializeToString,
            ),
            'GetWorkflow': grpc.unary_unary_rpc_method_handler(
                    servicer.GetWorkflow,
                    request_deserializer=ojs_dot_v1_dot_workflow__pb2.GetWorkflowRequest.FromString,
                    response_serializer=ojs_dot_v1_dot_workflow__pb2.GetWorkflowResponse.SerializeToString,
            ),
            'CancelWorkflow': grpc.unary_unary_rpc_method_handler(
                    servicer.CancelWorkflow,
                    request_deserializer=ojs_dot_v1_dot_workflow__pb2.CancelWorkflowRequest.FromString,
                    response_serializer=ojs_dot_v1_dot_workflow__pb2.CancelWorkflowResponse.SerializeToString,
            ),
            'SaveCheckpoint': grpc.unary_unary_rpc_method_handler(
                    servicer.SaveCheckpoint,
                    request_deserializer=ojs_dot_v1_dot_service__pb2.SaveCheckpointRequest.FromString,
                    response_serializer=ojs_dot_v1_dot_service__pb2.SaveCheckpointResponse.SerializeToString,
            ),
            'GetCheckpoint': grpc.unary_unary_rpc_method_handler(
                    servicer.GetCheckpoint,
                    request_deserializer=ojs_dot_v1_dot_service__pb2.GetCheckpointRequest.FromString,
                    response_serializer=ojs_dot_v1_dot_service__pb2.GetCheckpointResponse.SerializeToString,
            ),
            'DeleteCheckpoint': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteCheckpoint,
                    request_deserializer=ojs_dot_v1_dot_service__pb2.DeleteCheckpointRequest.FromString,
                    response_serializer=ojs_dot_v1_dot_service__pb2.DeleteCheckpointResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'ojs.v1.OJSService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('ojs.v1.OJSService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class OJSService:
    """OJSService is the gRPC service for the Open Job Spec protocol binding.

    Implementations MUST implement all RPCs corresponding to their declared
    conformance level. Implementations MUST NOT remove or rename any RPC method;
    unsupported methods MUST return UNIMPLEMENTED.

    Conformance levels:
    Level 0 (Core):          Manifest, Health, Enqueue, Fetch, Ack, Nack, ListQueues
    Level 1 (Reliable):      Level 0 + GetJob, CancelJob, Heartbeat, ListDeadLetter,
    RetryDeadLetter, DeleteDeadLetter
    Level 2 (Scheduled):     Level 1 + RegisterCron, UnregisterCron, ListCron
    Level 3 (Orchestration): Level 2 + CreateWorkflow, GetWorkflow, CancelWorkflow
    Level 4 (Advanced):      Level 3 + EnqueueBatch, QueueStats, PauseQueue, ResumeQueue
    Optional (any level):    StreamJobs, StreamEvents

    See: ojs-grpc-binding.md Section 5 (Protobuf Service Definition),
    Section 15 (Conformance Requirements)
    See: ojs-conformance.md
    ===========================================================================
    System RPCs
    ===========================================================================
    """

    @staticmethod
    def Manifest(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ojs.v1.OJSService/Manifest',
            ojs_dot_v1_dot_service__pb2.ManifestRequest.SerializeToString,
            ojs_dot_v1_dot_service__pb2.ManifestResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Health(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ojs.v1.OJSService/Health',
            ojs_dot_v1_dot_service__pb2.HealthRequest.SerializeToString,
            ojs_dot_v1_dot_service__pb2.HealthResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Enqueue(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ojs.v1.OJSService/Enqueue',
            ojs_dot_v1_dot_job__pb2.EnqueueRequest.SerializeToString,
            ojs_dot_v1_dot_job__pb2.EnqueueResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def EnqueueBatch(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ojs.v1.OJSService/EnqueueBatch',
            ojs_dot_v1_dot_job__pb2.EnqueueBatchRequest.SerializeToString,
            ojs_dot_v1_dot_job__pb2.EnqueueBatchResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetJob(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ojs.v1.OJSService/GetJob',
            ojs_dot_v1_dot_job__pb2.GetJobRequest.SerializeToString,
            ojs_dot_v1_dot_job__pb2.GetJobResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CancelJob(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ojs.v1.OJSService/CancelJob',
            ojs_dot_v1_dot_job__pb2.CancelJobRequest.SerializeToString,
            ojs_dot_v1_dot_job__pb2.CancelJobResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Fetch(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ojs.v1.OJSService/Fetch',
            ojs_dot_v1_dot_worker__pb2.FetchRequest.SerializeToString,
            ojs_dot_v1_dot_worker__pb2.FetchResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Ack(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ojs.v1.OJSService/Ack',
            ojs_dot_v1_dot_worker__pb2.AckRequest.SerializeToString,
            ojs_dot_v1_dot_worker__pb2.AckResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Nack(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ojs.v1.OJSService/Nack',
            ojs_dot_v1_dot_worker__pb2.NackRequest.SerializeToString,
            ojs_dot_v1_dot_worker__pb2.NackResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Heartbeat(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ojs.v1.OJSService/Heartbeat',
            ojs_dot_v1_dot_worker__pb2.HeartbeatRequest.SerializeToString,
            ojs_dot_v1_dot_worker__pb2.HeartbeatResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StreamJobs(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/ojs.v1.OJSService/StreamJobs',
            ojs_dot_v1_dot_worker__pb2.StreamJobsRequest.SerializeToString,
            ojs_dot_v1_dot_job__pb2.Job.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StreamEvents(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/ojs.v1.OJSService/StreamEvents',
            ojs_dot_v1_dot_events__pb2.StreamEventsRequest.SerializeToString,
            ojs_dot_v1_dot_events__pb2.Event.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListQueues(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ojs.v1.OJSService/ListQueues',
            ojs_dot_v1_dot_queue__pb2.ListQueuesRequest.SerializeToString,
            ojs_dot_v1_dot_queue__pb2.ListQueuesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def QueueStats(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ojs.v1.OJSService/QueueStats',
            ojs_dot_v1_dot_queue__pb2.QueueStatsRequest.SerializeToString,
            ojs_dot_v1_dot_queue__pb2.QueueStatsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def PauseQueue(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ojs.v1.OJSService/PauseQueue',
            ojs_dot_v1_dot_queue__pb2.PauseQueueRequest.SerializeToString,
            ojs_dot_v1_dot_queue__pb2.PauseQueueResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ResumeQueue(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ojs.v1.OJSService/ResumeQueue',
            ojs_dot_v1_dot_queue__pb2.ResumeQueueRequest.SerializeToString,
            ojs_dot_v1_dot_queue__pb2.ResumeQueueResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListDeadLetter(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ojs.v1.OJSService/ListDeadLetter',
            ojs_dot_v1_dot_queue__pb2.ListDeadLetterRequest.SerializeToString,
            ojs_dot_v1_dot_queue__pb2.ListDeadLetterResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RetryDeadLetter(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ojs.v1.OJSService/RetryDeadLetter',
            ojs_dot_v1_dot_queue__pb2.RetryDeadLetterRequest.SerializeToString,
            ojs_dot_v1_dot_queue__pb2.RetryDeadLetterResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeleteDeadLetter(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ojs.v1.OJSService/DeleteDeadLetter',
            ojs_dot_v1_dot_queue__pb2.DeleteDeadLetterRequest.SerializeToString,
            ojs_dot_v1_dot_queue__pb2.DeleteDeadLetterResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RegisterCron(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ojs.v1.OJSService/RegisterCron',
            ojs_dot_v1_dot_service__pb2.RegisterCronRequest.SerializeToString,
            ojs_dot_v1_dot_service__pb2.RegisterCronResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UnregisterCron(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ojs.v1.OJSService/UnregisterCron',
            ojs_dot_v1_dot_service__pb2.UnregisterCronRequest.SerializeToString,
            ojs_dot_v1_dot_service__pb2.UnregisterCronResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListCron(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ojs.v1.OJSService/ListCron',
            ojs_dot_v1_dot_service__pb2.ListCronRequest.SerializeToString,
            ojs_dot_v1_dot_service__pb2.ListCronResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CreateWorkflow(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ojs.v1.OJSService/CreateWorkflow',
            ojs_dot_v1_dot_workflow__pb2.CreateWorkflowRequest.SerializeToString,
            ojs_dot_v1_dot_workflow__pb2.CreateWorkflowResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetWorkflow(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ojs.v1.OJSService/GetWorkflow',
            ojs_dot_v1_dot_workflow__pb2.GetWorkflowRequest.SerializeToString,
            ojs_dot_v1_dot_workflow__pb2.GetWorkflowResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CancelWorkflow(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ojs.v1.OJSService/CancelWorkflow',
            ojs_dot_v1_dot_workflow__pb2.CancelWorkflowRequest.SerializeToString,
            ojs_dot_v1_dot_workflow__pb2.CancelWorkflowResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SaveCheckpoint(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ojs.v1.OJSService/SaveCheckpoint',
            ojs_dot_v1_dot_service__pb2.SaveCheckpointRequest.SerializeToString,
            ojs_dot_v1_dot_service__pb2.SaveCheckpointResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetCheckpoint(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ojs.v1.OJSService/GetCheckpoint',
            ojs_dot_v1_dot_service__pb2.GetCheckpointRequest.SerializeToString,
            ojs_dot_v1_dot_service__pb2.GetCheckpointResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeleteCheckpoint(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ojs.v1.OJSService/DeleteCheckpoint',
            ojs_dot_v1_dot_service__pb2.DeleteCheckpointRequest.SerializeToString,
            ojs_dot_v1_dot_service__pb2.DeleteCheckpointResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
