# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: ojs/v1/worker.proto
# Protobuf Python Version: 7.35.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    1,
    '',
    'ojs/v1/worker.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import duration_pb2 as google_dot_protobuf_dot_duration__pb2
from google.protobuf import struct_pb2 as google_dot_protobuf_dot_struct__pb2
from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2
from ojs._generated.ojs.v1 import job_pb2 as ojs_dot_v1_dot_job__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x13ojs/v1/worker.proto\x12\x06ojs.v1\x1a\x1egoogle/protobuf/duration.proto\x1a\x1cgoogle/protobuf/struct.proto\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x10ojs/v1/job.proto\"@\n\x0c\x46\x65tchRequest\x12\x0e\n\x06queues\x18\x01 \x03(\t\x12\r\n\x05\x63ount\x18\x02 \x01(\x05\x12\x11\n\tworker_id\x18\x03 \x01(\t\"*\n\rFetchResponse\x12\x19\n\x04jobs\x18\x01 \x03(\x0b\x32\x0b.ojs.v1.Job\"E\n\nAckRequest\x12\x0e\n\x06job_id\x18\x01 \x01(\t\x12\'\n\x06result\x18\x02 \x01(\x0b\x32\x17.google.protobuf.Struct\"#\n\x0b\x41\x63kResponse\x12\x14\n\x0c\x61\x63knowledged\x18\x01 \x01(\x08\">\n\x0bNackRequest\x12\x0e\n\x06job_id\x18\x01 \x01(\t\x12\x1f\n\x05\x65rror\x18\x02 \x01(\x0b\x32\x10.ojs.v1.JobError\"d\n\x0cNackResponse\x12\x1f\n\x05state\x18\x01 \x01(\x0e\x32\x10.ojs.v1.JobState\x12\x33\n\x0fnext_attempt_at\x18\x02 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\"\x8b\x01\n\x10HeartbeatRequest\x12\n\n\x02id\x18\x01 \x01(\t\x12\x11\n\tworker_id\x18\x02 \x01(\t\x12,\n\textend_by\x18\x03 \x01(\x0b\x32\x19.google.protobuf.Duration\x12*\n\rcurrent_state\x18\x04 \x01(\x0e\x32\x13.ojs.v1.WorkerState\"r\n\x11HeartbeatResponse\x12+\n\x0e\x64irected_state\x18\x01 \x01(\x0e\x32\x13.ojs.v1.WorkerState\x12\x30\n\x0cnew_deadline\x18\x02 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\"N\n\x11StreamJobsRequest\x12\x0e\n\x06queues\x18\x01 \x03(\t\x12\x11\n\tworker_id\x18\x02 \x01(\t\x12\x16\n\x0emax_concurrent\x18\x03 \x01(\x05*y\n\x0bWorkerState\x12\x1c\n\x18WORKER_STATE_UNSPECIFIED\x10\x00\x12\x18\n\x14WORKER_STATE_RUNNING\x10\x01\x12\x16\n\x12WORKER_STATE_QUIET\x10\x02\x12\x1a\n\x16WORKER_STATE_TERMINATE\x10\x03\x42P\n\x16org.openjobspec.ojs.v1P\x01Z4github.com/openjobspec/ojs-proto/gen/go/ojs/v1;ojsv1b\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'ojs.v1.worker_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\026org.openjobspec.ojs.v1P\001Z4github.com/openjobspec/ojs-proto/gen/go/ojs/v1;ojsv1'
  _globals['_WORKERSTATE']._serialized_start=866
  _globals['_WORKERSTATE']._serialized_end=987
  _globals['_FETCHREQUEST']._serialized_start=144
  _globals['_FETCHREQUEST']._serialized_end=208
  _globals['_FETCHRESPONSE']._serialized_start=210
  _globals['_FETCHRESPONSE']._serialized_end=252
  _globals['_ACKREQUEST']._serialized_start=254
  _globals['_ACKREQUEST']._serialized_end=323
  _globals['_ACKRESPONSE']._serialized_start=325
  _globals['_ACKRESPONSE']._serialized_end=360
  _globals['_NACKREQUEST']._serialized_start=362
  _globals['_NACKREQUEST']._serialized_end=424
  _globals['_NACKRESPONSE']._serialized_start=426
  _globals['_NACKRESPONSE']._serialized_end=526
  _globals['_HEARTBEATREQUEST']._serialized_start=529
  _globals['_HEARTBEATREQUEST']._serialized_end=668
  _globals['_HEARTBEATRESPONSE']._serialized_start=670
  _globals['_HEARTBEATRESPONSE']._serialized_end=784
  _globals['_STREAMJOBSREQUEST']._serialized_start=786
  _globals['_STREAMJOBSREQUEST']._serialized_end=864
# @@protoc_insertion_point(module_scope)
