name: Dependabot Automerge

on:
  pull_request_target:
    branches: [main]

permissions:
  contents: write
  pull-requests: write

jobs:
  automerge:
    if: github.actor == 'dependabot[bot]'
    uses: openjobspec/.github/.github/workflows/dependabot-automerge.yml@baf3b6896d4578c5586ef692daf7958f8e9a2d8a
